ALTER TABLE pages DROP COLUMN c, DROP COLUMN d; -- Видалення стовпчика
ALTER TABLE pages ENGINE = InnoDB; -- Зміна зберігання двигуна
ALTER TABLE pages ROW_FORMAT = COMPRESSED; -- Зміна формату зберігання данних
ALTER TABLE pages ENCRYPTION='Y';
ALTER TABLE pages ENCRYPTION='N'; -- Вкл/Викл табличного шифрування
ALTER TABLE pages AUTO_INCREMENT = 13; -- зміна поточного значення AUTO_INCREMENT 
ALTER TABLE pages CHARACTER SET = utf8; -- зміна кодування за замовчуванням
ALTER TABLE pages COMMENT = 'New table comment'; -- додати/змінити коментар до таблиці
ALTER TABLE pages CHANGE a b INTEGER; -- зміна імені колонки з a на b та зміна типу на INTEGER
ALTER TABLE pages CHANGE b b BIGINT NOT NULL; -- зміна типу на BIGINT
ALTER TABLE pages MODIFY b BIGINT NOT NULL; -- зміна типу на BIGINT без перейменовування
ALTER TABLE pages DROP FOREIGN KEY fk_symbol; -- видалення зовнішнього ключа
ALTER TABLE pages CONVERT TO CHARACTER SET charset_name; -- зміна набору символів
ALTER TABLE pages MODIFY latin1_text_col TEXT CHARACTER SET utf8;
ALTER TABLE pages MODIFY latin1_varchar_col VARCHAR(M) CHARACTER SET utf8; -- зміна окремого стовпчика набору символів
ALTER TABLE pages DEFAULT CHARACTER SET charset_name; -- зміна за замовчуванням набору символів
ALTER TABLE pages PARTITION BY HASH(id) PARTITIONS 8; -- розбиття таблиці на логічні частини
CREATE TABLE t1 (id INT, year_col INT) 
PARTITION BY RANGE (year_col) (
    PARTITION p0 VALUES LESS THAN (1991),
    PARTITION p1 VALUES LESS THAN (1995),
    PARTITION p2 VALUES LESS THAN (1999) ); -- Створення таблиці та установлення PARTITION
ALTER TABLE t1 ADD PARTITION (PARTITION p3 VALUES LESS THAN (2002)) -- додавання PARTITION
ALTER TABLE t1 ADD PARTITION (PARTITION p4 VALUES LESS THAN (2015) TABLESPACE = `ts1`);
ALTER TABLE t1 ADD PARTITION (PARTITION p4 VALUES LESS THAN (2015) TABLESPACE = `innodb_file_per_table`);
ALTER TABLE t1 ADD PARTITION (PARTITION p4 VALUES LESS THAN (2015) TABLESPACE = `innodb_system`);
ALTER TABLE t1 DROP PARTITION p0, p1;
ALTER TABLE t1 DISCARD PARTITION p2, p3 TABLESPACE;
ALTER TABLE t1 IMPORT PARTITION p2, p3 TABLESPACE;
ALTER TABLE table ALGORITHM=INPLACE, REORGANIZE PARTITION;
SELECT PARTITION_NAME, TABLE_ROWS
    FROM INFORMATION_SCHEMA.PARTITIONS
    WHERE TABLE_NAME = 't1';
ALTER TABLE table ALGORITHM=INPLACE, REORGANIZE PARTITION;
ALTER TABLE t1 ANALYZE PARTITION p1, p2;
ALTER TABLE t1 CHECK PARTITION p2;
ALTER TABLE t1 ADD COLUMN c3 INT COLUMN_FORMAT DYNAMIC STORAGE MEMORY, ALGORITHM=INPLACE;
ALTER TABLE t2 ADD COLUMN c2 INT, ADD COLUMN c3 INT, ALGORITHM=INPLACE;

ALTER TABLE t1 RENAME t2;
ALTER TABLE t2 MODIFY a TINYINT NOT NULL, CHANGE b c CHAR(20);
ALTER TABLE t2 ADD d TIMESTAMP;
ALTER TABLE t2 ADD INDEX (d), ADD PRIMARY KEY (a);
ALTER TABLE t2 DROP COLUMN c;
ALTER TABLE t2 ADD c INT UNSIGNED NOT NULL AUTO_INCREMENT, ADD INDEX (c);
ALTER TABLE t2 ADD INDEX (d), ADD UNIQUE (a);
ALTER TABLE t2 ADD c INT UNSIGNED NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (c);
ALTER TABLE t2 TABLESPACE ts_1 STORAGE DISK;
ALTER TABLE t2 MODIFY c3 INT STORAGE MEMORY;
ALTER TABLE t2 ADD id INT AUTO_INCREMENT PRIMARY KEY;